apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-admin-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: superset-admin-secret       # name of the k8s Secret to be created
  data:
  - secretKey: password
    remoteRef:
      key: initial-secret
      property: GRAFANA_PASSWORD # ยืมมาใช้ก่อน
