apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 9.1.9
  targetNamespace: argocd
  valuesContent: |-
    fullnameOverride: argocd
    dex: {}
---    
    #server:  
    #  config:
    #    url: https://github.com/wintech-thai/otep-dc-k3s.git
