apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nifikop
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'nifikop-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/wintech-thai/otep-dc-k3s.git
        targetRevision: "{{name}}" #Based on environment
        path: '99-deployments/manifests/nifikop'
      destination:
        name: in-cluster
        namespace: nifikop
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
